# Generated by Django 4.0.2 on 2022-02-07 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True, verbose_name='User Bio')),
                ('mobile', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=255, verbose_name='User Address')),
                ('location', models.CharField(max_length=50, verbose_name='Genral Location')),
                ('pincode', models.CharField(max_length=6)),
                ('is_prime', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentUserProfile',
            fields=[
                ('templateuserprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.templateuserprofile')),
                ('user_type', models.CharField(default='Agent', max_length=6)),
            ],
            bases=('profiles.templateuserprofile',),
        ),
        migrations.CreateModel(
            name='BuyerUserProfile',
            fields=[
                ('templateuserprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.templateuserprofile')),
                ('user_type', models.CharField(default='Buyer', max_length=6)),
            ],
            bases=('profiles.templateuserprofile',),
        ),
        migrations.CreateModel(
            name='SellerUserProfile',
            fields=[
                ('templateuserprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.templateuserprofile')),
                ('user_type', models.CharField(default='Seller', max_length=6)),
            ],
            bases=('profiles.templateuserprofile',),
        ),
    ]
