# Generated by Django 4.0.2 on 2022-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prime', models.BooleanField(default=False)),
                ('subscription_period', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='User Bio')),
                ('mobile', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('is_verified', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('Agent', 'Agent'), ('Buyer/Owner', 'Buyer/Owner'), ('Builder', 'Builder')], max_length=11)),
                ('contacted_by', models.ManyToManyField(blank=True, related_name='contacted_by', to='profiles.Contacted')),
                ('contacted_to', models.ManyToManyField(blank=True, related_name='contacted_to', to='profiles.Contacted')),
            ],
        ),
    ]
