# Generated by Django 4.0.2 on 2022-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertymodel_visits'),
        ('profiles', '0002_agentuserprofile_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentuserprofile',
            name='properties',
            field=models.ManyToManyField(null=True, related_name='agent_properties', to='properties.PropertyModel'),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='agent_whitelist', to='properties.PropertyModel'),
        ),
        migrations.AlterField(
            model_name='buyeruserprofile',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='buyer_wishlist', to='properties.PropertyModel'),
        ),
        migrations.AlterField(
            model_name='selleruserprofile',
            name='properties',
            field=models.ManyToManyField(null=True, related_name='seller_properties', to='properties.PropertyModel'),
        ),
    ]
