# Generated by Django 4.0.2 on 2022-02-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertymodel_visits'),
        ('profiles', '0003_alter_agentuserprofile_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentuserprofile',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='agent_properties', to='properties.PropertyModel'),
        ),
    ]
