# Generated by Django 4.0.2 on 2022-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_contacted_property_alter_contacted_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='bio',
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone Number'),
        ),
    ]
