# Generated by Django 4.0.2 on 2022-02-07 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_propertymodel_visits'),
        ('profiles', '0005_alter_agentuserprofile_wishlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True, verbose_name='User Bio')),
                ('mobile', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=255, verbose_name='User Address')),
                ('location', models.CharField(max_length=50, verbose_name='Genral Location')),
                ('pincode', models.CharField(max_length=6)),
                ('is_prime', models.BooleanField(default=False)),
                ('user_type', models.CharField(default='Agent', max_length=6)),
                ('properties', models.ManyToManyField(blank=True, related_name='properties', to='properties.PropertyModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='wishlist', to='properties.PropertyModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='buyeruserprofile',
            name='templateuserprofile_ptr',
        ),
        migrations.RemoveField(
            model_name='buyeruserprofile',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='selleruserprofile',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='selleruserprofile',
            name='templateuserprofile_ptr',
        ),
        migrations.RemoveField(
            model_name='templateuserprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AgentUserProfile',
        ),
        migrations.DeleteModel(
            name='BuyerUserProfile',
        ),
        migrations.DeleteModel(
            name='SellerUserProfile',
        ),
        migrations.DeleteModel(
            name='TemplateUserProfile',
        ),
    ]
