# Generated by Django 4.0.2 on 2022-02-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofilemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user_type',
            field=models.CharField(choices=[('A', 'Agent'), ('B', 'Buyer'), ('S', 'Seller')], max_length=1),
        ),
    ]
