# Generated by Django 4.0.2 on 2022-02-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofilemodel_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='state',
            field=models.CharField(default=1, max_length=50, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='bio',
            field=models.TextField(blank=True, verbose_name='User Bio'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=6),
        ),
    ]
