# Generated by Django 4.0.2 on 2022-02-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_image_propertymodel_image'),
        ('profiles', '0008_remove_userprofilemodel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover', to='properties.image'),
        ),
    ]
