# Generated by Django 4.0.2 on 2022-02-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userprofilemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Buyer/Owner', 'Buyer/Owner'), ('Builder', 'Builder')], max_length=11),
        ),
    ]
