# Generated by Django 4.0.2 on 2022-02-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_userprofilemodel_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='pincode',
        ),
    ]
