# Generated by Django 4.0.2 on 2022-02-16 19:12

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=80)),
                ('property_name', models.TextField(max_length=80)),
                ('description', models.TextField(null=True, verbose_name='Property Description')),
                ('address', models.CharField(max_length=255, verbose_name='Property Address')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('pincode', models.CharField(max_length=6)),
                ('prime_property', models.BooleanField(default=False)),
                ('price', models.BigIntegerField()),
                ('property_size', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('corner', models.BooleanField(blank=True)),
                ('gated', models.BooleanField(blank=True)),
                ('availability', models.DateTimeField()),
                ('furnishing_status', models.CharField(choices=[('furnished', 'Furnished'), ('semifurnished', 'Semi furnished'), ('unfurnished', 'Unfurnished')], max_length=25)),
                ('for_status', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('pg', 'Paying Geust')], max_length=4)),
                ('bathrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=2)),
                ('bedrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], max_length=2)),
                ('possession', models.CharField(choices=[('Under Construction', 'Under Construction'), ('Ready To Move', 'Ready To Move')], max_length=25)),
                ('property_type', models.CharField(choices=[('VI', 'Villa'), ('FL', 'Flat'), ('CM', 'Commercial'), ('PT', 'Plot')], max_length=2)),
                ('floor', models.CharField(choices=[('Basement', 'Basement'), ('Ground', 'Ground'), ('1-4', '1-4'), ('5-8', '5-8'), ('9-12', '9-12'), ('13+', '13+')], max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visits', models.IntegerField(default=0)),
                ('amenities', models.ManyToManyField(blank=True, related_name='amenities', to='properties.AmenitiesTags')),
                ('image', models.ManyToManyField(blank=True, related_name='products', to='properties.Image')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='profiles.userprofilemodel')),
                ('wished_by', models.ManyToManyField(blank=True, related_name='wished_by', to='profiles.UserProfileModel')),
            ],
        ),
    ]
