# Generated by Django 4.0.2 on 2022-02-07 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=80)),
                ('description', models.TextField(null=True, verbose_name='User Bio')),
                ('address', models.CharField(max_length=255, verbose_name='User Address')),
                ('location', models.CharField(max_length=50, verbose_name='Genral Location')),
                ('pincode', models.CharField(max_length=6)),
                ('prime_property', models.BooleanField(default=False)),
                ('price', models.BigIntegerField()),
                ('property_size', models.SmallIntegerField()),
                ('furnishing_status', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('availability', models.CharField(max_length=100)),
                ('bedrooms', models.SmallIntegerField()),
                ('bathrooms', models.SmallIntegerField()),
                ('property_type', models.CharField(choices=[('A', 'Apartment'), ('I', 'Independent House'), ('V', 'Villa'), ('B', 'Builder Floor'), ('P', 'Penthouse'), ('S', 'Studio Apartment'), ('O', 'Other')], max_length=2)),
                ('url', models.URLField()),
                ('amenities', models.ManyToManyField(related_name='libraries', to='properties.AmenitiesTags')),
                ('features', models.ManyToManyField(related_name='libraries', to='properties.FeaturesTags')),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
