# Generated by Django 4.0.2 on 2022-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
