# Generated by Django 4.0.2 on 2022-02-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='location',
            field=models.CharField(default='dharavi', max_length=50, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
