# Generated by Django 4.0.2 on 2022-02-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sublocationmodel',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='sublocationmodel',
            name='sublocations',
        ),
        migrations.DeleteModel(
            name='Sublocation',
        ),
        migrations.AddField(
            model_name='citymodel',
            name='sublocations',
            field=models.ManyToManyField(related_name='city_sublocation', to='properties.SublocationModel'),
        ),
    ]
