# Generated by Django 4.0.2 on 2022-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertymodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='floor',
            field=models.CharField(choices=[('Basement', 'Basement'), ('Ground', 'Ground'), ('1-4', '1-4'), ('5-8', '5-8'), ('9-12', '9-12'), ('13+', '13+')], default='Ground', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='property_type',
            field=models.CharField(choices=[('VI', 'Villa'), ('FL', 'Flat'), ('CM', 'Commercial'), ('PT', 'Plot')], max_length=2),
        ),
    ]
