# Generated by Django 4.0.2 on 2022-02-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertymodel_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymodel',
            name='url',
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Property Address'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='amenities',
            field=models.ManyToManyField(related_name='amenities', to='properties.AmenitiesTags'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='description',
            field=models.TextField(null=True, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='features',
            field=models.ManyToManyField(related_name='features', to='properties.FeaturesTags'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='property_type',
            field=models.CharField(choices=[('AP', 'Apartment'), ('IH', 'Independent House'), ('VI', 'Villa'), ('BF', 'Builder Floor'), ('PH', 'Penthouse'), ('SA', 'Studio Apartment'), ('OT', 'Other')], max_length=2),
        ),
    ]
