# Generated by Django 4.0.2 on 2022-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertymodel_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('furnished', 'Furnished'), ('semifurnished', 'Semi furnished'), ('unfurnished', 'Unfurnished')], max_length=25, null=True),
        ),
    ]
