# Generated by Django 4.0.2 on 2022-02-07 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_remove_propertymodel_url_alter_propertymodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
