# Generated by Django 4.0.2 on 2022-02-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertymodel_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymodel',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='state',
            field=models.CharField(default=1, max_length=50, verbose_name='Genral Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='amenities', to='properties.AmenitiesTags'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features', to='properties.FeaturesTags'),
        ),
    ]
