# Generated by Django 4.0.2 on 2022-02-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_location_propertymodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='property_name',
            field=models.TextField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
