# Generated by Django 4.0.2 on 2022-02-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertymodel_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
