# Generated by Django 4.0.2 on 2022-02-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_image_propertymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='for_status',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='postion',
            field=models.CharField(choices=[('UC', 'Under Construction'), ('RD', 'Ready To Move')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='availability',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='bedrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='furnishing_status',
            field=models.CharField(choices=[('furnished', 'Furninshed'), ('unfurnished', 'Semi furnished'), ('nonfurnished', 'Non Furnished')], max_length=12),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='property_size',
            field=models.IntegerField(),
        ),
    ]
