# Generated by Django 4.0.2 on 2022-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertymodel_for_status_propertymodel_postion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymodel',
            name='postion',
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='possession',
            field=models.CharField(choices=[('Under Construction', 'Under Construction'), ('Ready To Move', 'Ready To Move')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='bedrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='furnishing_status',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semifurnished', 'Semi furnished'), ('unfurnished', 'Unfurnished')], max_length=25),
        ),
    ]
