# Generated by Django 4.0.2 on 2022-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_propertymodel_postion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='products', to='properties.Image'),
        ),
    ]
