# Generated by Django 4.0.2 on 2022-02-10 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0011_alter_propertymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='whished_by',
            field=models.ManyToManyField(blank=True, related_name='wished_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
