# Generated by Django 4.0.2 on 2022-02-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Janmejay', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
