# Generated by Django 4.0.2 on 2022-02-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
